export const AUTHENTICATE_AZURE = "AUTHENTICATE_AZURE";
export const AUTHENTICATE_DOCKER = "AUTHENTICATE_DOCKER";
export const IMPORT_REPOSITORY = "IMPORT_REPOSITORY";
export const CHANGE_MODE = "CHANGE_MODE";